# Generated by Django 5.0.4 on 2024-04-12 16:52

import ai_models.models
import utils.string
import utils.validation
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_file",
                    models.FileField(
                        upload_to=ai_models.models.upload_path,
                        validators=[utils.validation.validate_model_extension],
                    ),
                ),
                (
                    "classes_file",
                    models.FileField(
                        upload_to=ai_models.models.upload_path,
                        validators=[utils.validation.validate_classes_file],
                    ),
                ),
                (
                    "resize",
                    models.CharField(
                        default="224, 224",
                        max_length=100,
                        validators=[utils.string.validate_int_list],
                    ),
                ),
                (
                    "mean",
                    models.CharField(
                        default="0.4708, 0.4602, 0.4550",
                        max_length=100,
                        validators=[utils.string.validate_float_list],
                    ),
                ),
                (
                    "std",
                    models.CharField(
                        default="0.2593, 0.2584, 0.2634",
                        max_length=100,
                        validators=[utils.string.validate_float_list],
                    ),
                ),
            ],
        ),
    ]
